name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  - gpt-3.5-turbo-0125
